name: "Terraform"

on:
  push:
    branches: [ "main" ]
    paths: [ "infra/**" ]
  workflow_dispatch:


jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: "Checkout"
      uses: actions/checkout@v4


    - name: "Terraform Init"
<<<<<<< HEAD
=======
      working-directory: ./infra
>>>>>>> 0d6c4dd06f4c9ad6d905276c1f4730040148512a
      run: terraform init \ -backend-config="bucket=${{ secrets.BUCKET }}" \ -backend-config="key=${{ secrets.KEY }}" \ -backend-config="region=us-east-1"

    - name: "Terraform Apply"
      working-directory: ./infra
      run: terraform apply -auto-approve
